#This is  a CI pipeline where we build an image and deployed to DockerHub which will generat SBOM,Artifacts.

name: Php application to build the images
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dev/deployment.yaml**'
      - 'argorollouts/argo-rollout.yaml**'
      - 'README.md'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # This job runs on the latest version of Ubuntu.
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    # Check out the code from the repository to the GitHub Actions runner.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # Sets up Docker Buildx, which is an advance feature for building Docker images.

    - name: Build Docker image
      run: docker build -t meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}  -f files/Dockerfile .
    # Builds the Docker image using the Dockerfile located in 'file/Dockerfile'.
    #The image is tagged with 'meghakadur/argocd:1.0.RELEASE-' followed by the GitHub run number.

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #Log in to Docker Hub credentials stored in Github secrets

    - name: Push Docker image
      run: docker push meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}
    # Pushes the newly built docker image to DockerHub with the tag specified.

    - name: scanning for SBOM
      uses: anchore/sbom-action@v0
      with:
        image: meghakadur/argocd:1.0.RELEASE-${{ github.run_number }}
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
    # Uses Snchore to scan the Docker Image for software Bill of material (SBOM).
    # which provides detaisl about the software components and dependencies.

    - uses: actions/checkout@v3
    # Checks out the repository code again to ensure  that any changes made in the previous steps are included.
    - uses: advanced-security/sbom-generator-action@v0.0.1
      id: sbom
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_TOKEN }}
        #GITHUB_TOKEN: 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
    # Generates an SBOM
    - uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{steps.sbom.outputs.fileName }}
        name: "SBOM"
    # Uploads the generated SBOM as an artifact 

  modifygit:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'megha-6/gitautomate'
          token: ${{ secrets.NEW_TOKEN }}
    
      - name: modify the image
        run: |
          git config user.email meghakadur691993@gmail.com
          git config user.name megha-6
          pwd
          ls
          cd dev
          cat deployment.yaml
          pwd
          sed -i "s+meghakadur/argocd.*+meghakadur/argocd:1.0.RELEASE-$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USE }}R
          GIT_PASSWORD: ${{ secrets.GIT_PSW }}
          RUN_NUMBER: ${{ github.run_number }}
